# cython: boundscheck=False, wraparound=False, cdivision=True

#ATTENTION: THIS FILE IS GENERATED BY SCRIPTS/update_ability_mapping.py, DO NOT EDIT MANUALLY

cimport cython
from sc2.ids.ability_id import AbilityId



cdef int MAX_UNIT_KEY = 2200
cdef int MAX_UPGRADE_KEY = 400

cdef int mapping_unit_array[2200]
cdef int mapping_upgrade_array[400]

cdef public int RESEARCH_BUILDING_ARRAY[1000] #indexed by unit type id, value is 1 if its a research building, 0 otherwise
cdef public int STRUCT_ABILITIES[1620]


# Initialize mapping_unit_array, mapping_upgrade_array, RESEARCH_BUILDING_ARRAY, STRUCT_ABILITIES with -1 (or 0 for RESEARCH_BUILDING_ARRAY/STRUCT_ABILITIES)
for i in range(2200):
    mapping_unit_array[i] = -1
for i in range(400):
    mapping_upgrade_array[i] = -1
for i in range(1000):
    RESEARCH_BUILDING_ARRAY[i] = -1
for i in range(1620):
    STRUCT_ABILITIES[i] = -1


@cython.cfunc
@cython.inline
cpdef int map_unit_value(int key) nogil:
    if 0 <= key < MAX_UNIT_KEY:
        return mapping_unit_array[key]
    return -1

@cython.cfunc
@cython.inline
cpdef int map_upgrade_value(int key) nogil:
    if 0 <= key < MAX_UPGRADE_KEY:
        return mapping_upgrade_array[key]
    return -1





# Rewritten mappings from UNIT_TYPE_ID_TO_ABILITY_MAP, Updated at 2026-02-07 15:04:42.575288
mapping_unit_array[5] = 3682  # TECHLAB
mapping_unit_array[18] = 318  # COMMANDCENTER
mapping_unit_array[19] = 319  # SUPPLYDEPOT
mapping_unit_array[20] = 320  # REFINERY
mapping_unit_array[21] = 321  # BARRACKS
mapping_unit_array[22] = 322  # ENGINEERINGBAY
mapping_unit_array[23] = 323  # MISSILETURRET
mapping_unit_array[24] = 324  # BUNKER
mapping_unit_array[25] = 326  # SENSORTOWER
mapping_unit_array[26] = 327  # GHOSTACADEMY
mapping_unit_array[27] = 328  # FACTORY
mapping_unit_array[28] = 329  # STARPORT
mapping_unit_array[29] = 331  # ARMORY
mapping_unit_array[30] = 333  # FUSIONCORE
mapping_unit_array[37] = 421  # BARRACKSTECHLAB
mapping_unit_array[38] = 422  # BARRACKSREACTOR
mapping_unit_array[39] = 454  # FACTORYTECHLAB
mapping_unit_array[40] = 455  # FACTORYREACTOR
mapping_unit_array[41] = 487  # STARPORTTECHLAB
mapping_unit_array[42] = 488  # STARPORTREACTOR
mapping_unit_array[59] = 880  # NEXUS
mapping_unit_array[60] = 881  # PYLON
mapping_unit_array[61] = 882  # ASSIMILATOR
mapping_unit_array[62] = 883  # GATEWAY
mapping_unit_array[63] = 884  # FORGE
mapping_unit_array[64] = 885  # FLEETBEACON
mapping_unit_array[65] = 886  # TWILIGHTCOUNCIL
mapping_unit_array[66] = 887  # PHOTONCANNON
mapping_unit_array[67] = 889  # STARGATE
mapping_unit_array[68] = 890  # TEMPLARARCHIVE
mapping_unit_array[69] = 891  # DARKSHRINE
mapping_unit_array[70] = 892  # ROBOTICSBAY
mapping_unit_array[71] = 893  # ROBOTICSFACILITY
mapping_unit_array[72] = 894  # CYBERNETICSCORE
mapping_unit_array[86] = 1152  # HATCHERY
mapping_unit_array[88] = 1154  # EXTRACTOR
mapping_unit_array[89] = 1155  # SPAWNINGPOOL
mapping_unit_array[90] = 1156  # EVOLUTIONCHAMBER
mapping_unit_array[91] = 1157  # HYDRALISKDEN
mapping_unit_array[92] = 1158  # SPIRE
mapping_unit_array[93] = 1159  # ULTRALISKCAVERN
mapping_unit_array[94] = 1160  # INFESTATIONPIT
mapping_unit_array[95] = 1161  # NYDUSNETWORK
mapping_unit_array[96] = 1162  # BANELINGNEST
mapping_unit_array[97] = 1165  # ROACHWARREN
mapping_unit_array[98] = 1166  # SPINECRAWLER
mapping_unit_array[99] = 1167  # SPORECRAWLER
mapping_unit_array[100] = 1216  # LAIR
mapping_unit_array[101] = 1218  # HIVE
mapping_unit_array[130] = 1450  # PLANETARYFORTRESS
mapping_unit_array[132] = 1516  # ORBITALCOMMAND
mapping_unit_array[504] = 1163  # LURKERDENMP
mapping_unit_array[1910] = 895  # SHIELDBATTERY
mapping_unit_array[1943] = 320  # REFINERYRICH
mapping_unit_array[1994] = 882  # ASSIMILATORRICH
mapping_unit_array[1995] = 1154  # EXTRACTORRICH

# UPGRADE_ID_TO_ABILITY_MAP
mapping_upgrade_array[2] = 216  # GLIALRECONSTITUTION
mapping_upgrade_array[3] = 217  # TUNNELINGCLAWS
mapping_upgrade_array[4] = 265  # CHITINOUSPLATING
mapping_upgrade_array[5] = 650  # HISECAUTOTRACKING
mapping_upgrade_array[6] = 651  # TERRANBUILDINGARMOR
mapping_upgrade_array[7] = 652  # TERRANINFANTRYWEAPONSLEVEL1
mapping_upgrade_array[8] = 653  # TERRANINFANTRYWEAPONSLEVEL2
mapping_upgrade_array[9] = 654  # TERRANINFANTRYWEAPONSLEVEL3
mapping_upgrade_array[11] = 656  # TERRANINFANTRYARMORSLEVEL1
mapping_upgrade_array[12] = 657  # TERRANINFANTRYARMORSLEVEL2
mapping_upgrade_array[13] = 658  # TERRANINFANTRYARMORSLEVEL3
mapping_upgrade_array[15] = 730  # STIMPACK
mapping_upgrade_array[16] = 731  # SHIELDWALL
mapping_upgrade_array[17] = 732  # PUNISHERGRENADES
mapping_upgrade_array[19] = 761  # HIGHCAPACITYBARRELS
mapping_upgrade_array[20] = 790  # BANSHEECLOAK
mapping_upgrade_array[21] = 1535  # MEDIVACCADUCEUSREACTOR
mapping_upgrade_array[25] = 820  # PERSONALCLOAKING
mapping_upgrade_array[30] = 855  # TERRANVEHICLEWEAPONSLEVEL1
mapping_upgrade_array[31] = 856  # TERRANVEHICLEWEAPONSLEVEL2
mapping_upgrade_array[32] = 857  # TERRANVEHICLEWEAPONSLEVEL3
mapping_upgrade_array[36] = 861  # TERRANSHIPWEAPONSLEVEL1
mapping_upgrade_array[37] = 862  # TERRANSHIPWEAPONSLEVEL2
mapping_upgrade_array[38] = 863  # TERRANSHIPWEAPONSLEVEL3
mapping_upgrade_array[39] = 1062  # PROTOSSGROUNDWEAPONSLEVEL1
mapping_upgrade_array[40] = 1063  # PROTOSSGROUNDWEAPONSLEVEL2
mapping_upgrade_array[41] = 1064  # PROTOSSGROUNDWEAPONSLEVEL3
mapping_upgrade_array[42] = 1065  # PROTOSSGROUNDARMORSLEVEL1
mapping_upgrade_array[43] = 1066  # PROTOSSGROUNDARMORSLEVEL2
mapping_upgrade_array[44] = 1067  # PROTOSSGROUNDARMORSLEVEL3
mapping_upgrade_array[45] = 1068  # PROTOSSSHIELDSLEVEL1
mapping_upgrade_array[46] = 1069  # PROTOSSSHIELDSLEVEL2
mapping_upgrade_array[47] = 1070  # PROTOSSSHIELDSLEVEL3
mapping_upgrade_array[48] = 1093  # OBSERVERGRAVITICBOOSTER
mapping_upgrade_array[49] = 1094  # GRAVITICDRIVE
mapping_upgrade_array[50] = 1097  # EXTENDEDTHERMALLANCE
mapping_upgrade_array[52] = 1126  # PSISTORMTECH
mapping_upgrade_array[53] = 1186  # ZERGMELEEWEAPONSLEVEL1
mapping_upgrade_array[54] = 1187  # ZERGMELEEWEAPONSLEVEL2
mapping_upgrade_array[55] = 1188  # ZERGMELEEWEAPONSLEVEL3
mapping_upgrade_array[56] = 1189  # ZERGGROUNDARMORSLEVEL1
mapping_upgrade_array[57] = 1190  # ZERGGROUNDARMORSLEVEL2
mapping_upgrade_array[58] = 1191  # ZERGGROUNDARMORSLEVEL3
mapping_upgrade_array[59] = 1192  # ZERGMISSILEWEAPONSLEVEL1
mapping_upgrade_array[60] = 1193  # ZERGMISSILEWEAPONSLEVEL2
mapping_upgrade_array[61] = 1194  # ZERGMISSILEWEAPONSLEVEL3
mapping_upgrade_array[62] = 1223  # OVERLORDSPEED
mapping_upgrade_array[64] = 1225  # BURROW
mapping_upgrade_array[65] = 1252  # ZERGLINGATTACKSPEED
mapping_upgrade_array[66] = 1253  # ZERGLINGMOVEMENTSPEED
mapping_upgrade_array[68] = 1312  # ZERGFLYERWEAPONSLEVEL1
mapping_upgrade_array[69] = 1313  # ZERGFLYERWEAPONSLEVEL2
mapping_upgrade_array[70] = 1314  # ZERGFLYERWEAPONSLEVEL3
mapping_upgrade_array[71] = 1315  # ZERGFLYERARMORSLEVEL1
mapping_upgrade_array[72] = 1316  # ZERGFLYERARMORSLEVEL2
mapping_upgrade_array[73] = 1317  # ZERGFLYERARMORSLEVEL3
mapping_upgrade_array[75] = 1482  # CENTRIFICALHOOKS
mapping_upgrade_array[76] = 1532  # BATTLECRUISERENABLESPECIALIZATIONS
mapping_upgrade_array[78] = 1562  # PROTOSSAIRWEAPONSLEVEL1
mapping_upgrade_array[79] = 1563  # PROTOSSAIRWEAPONSLEVEL2
mapping_upgrade_array[80] = 1564  # PROTOSSAIRWEAPONSLEVEL3
mapping_upgrade_array[81] = 1565  # PROTOSSAIRARMORSLEVEL1
mapping_upgrade_array[82] = 1566  # PROTOSSAIRARMORSLEVEL2
mapping_upgrade_array[83] = 1567  # PROTOSSAIRARMORSLEVEL3
mapping_upgrade_array[84] = 1568  # WARPGATERESEARCH
mapping_upgrade_array[86] = 1592  # CHARGE
mapping_upgrade_array[87] = 1593  # BLINKTECH
mapping_upgrade_array[88] = 263  # ANABOLICSYNTHESIS
mapping_upgrade_array[99] = 46  # PHOENIXRANGEUPGRADE
mapping_upgrade_array[101] = 1455  # NEURALPARASITE
mapping_upgrade_array[116] = 864  # TERRANVEHICLEANDSHIPARMORSLEVEL1
mapping_upgrade_array[117] = 865  # TERRANVEHICLEANDSHIPARMORSLEVEL2
mapping_upgrade_array[118] = 866  # TERRANVEHICLEANDSHIPARMORSLEVEL3
mapping_upgrade_array[122] = 764  # DRILLCLAWS
mapping_upgrade_array[127] = 3710  # LURKERRANGE
mapping_upgrade_array[130] = 1594  # ADEPTPIERCINGATTACK
mapping_upgrade_array[134] = 1282  # EVOLVEGROOVEDSPINES
mapping_upgrade_array[135] = 1283  # EVOLVEMUSCULARAUGMENTS
mapping_upgrade_array[136] = 799  # BANSHEESPEED
mapping_upgrade_array[140] = 1533  # LIBERATORAGRANGEUPGRADE
mapping_upgrade_array[141] = 2720  # DARKTEMPLARBLINKUPGRADE
mapping_upgrade_array[144] = 769  # CYCLONELOCKONDAMAGEUPGRADE
mapping_upgrade_array[288] = 48  # VOIDRAYSPEEDUPGRADE
mapping_upgrade_array[289] = 766  # SMARTSERVOS
mapping_upgrade_array[293] = 3709  # DIGGINGCLAWS
mapping_upgrade_array[297] = 49  # TEMPESTGROUNDATTACKUPGRADE
mapping_upgrade_array[298] = 1284  # FRENZY
mapping_upgrade_array[300] = 807  # INTERFERENCEMATRIX

# STRUCT_ABILLITIES
STRUCT_ABILITIES[318] = 2  # TERRANBUILD_COMMANDCENTER
STRUCT_ABILITIES[421] = 1  # BUILD_TECHLAB_BARRACKS
STRUCT_ABILITIES[422] = 1  # BUILD_REACTOR_BARRACKS
STRUCT_ABILITIES[454] = 1  # BUILD_TECHLAB_FACTORY
STRUCT_ABILITIES[455] = 1  # BUILD_REACTOR_FACTORY
STRUCT_ABILITIES[487] = 1  # BUILD_TECHLAB_STARPORT
STRUCT_ABILITIES[488] = 1  # BUILD_REACTOR_STARPORT
STRUCT_ABILITIES[1152] = 2  # ZERGBUILD_HATCHERY
STRUCT_ABILITIES[1216] = 2  # UPGRADETOLAIR_LAIR
STRUCT_ABILITIES[1218] = 1  # UPGRADETOHIVE_HIVE
STRUCT_ABILITIES[1450] = 1  # UPGRADETOPLANETARYFORTRESS_PLANETARYFORTRESS
STRUCT_ABILITIES[1516] = 1  # UPGRADETOORBITAL_ORBITALCOMMAND

# RESEARCH_BUILDING_ARRAY
RESEARCH_BUILDING_ARRAY[63] = 1  # FORGE
RESEARCH_BUILDING_ARRAY[72] = 1  # CYBERNETICSCORE
RESEARCH_BUILDING_ARRAY[65] = 1  # TWILIGHTCOUNCIL
RESEARCH_BUILDING_ARRAY[70] = 1  # ROBOTICSBAY
RESEARCH_BUILDING_ARRAY[64] = 1  # FLEETBEACON
RESEARCH_BUILDING_ARRAY[68] = 1  # TEMPLARARCHIVE
RESEARCH_BUILDING_ARRAY[69] = 1  # DARKSHRINE
RESEARCH_BUILDING_ARRAY[29] = 1  # ARMORY
RESEARCH_BUILDING_ARRAY[22] = 1  # ENGINEERINGBAY
RESEARCH_BUILDING_ARRAY[5] = 1  # TECHLAB
RESEARCH_BUILDING_ARRAY[37] = 1  # BARRACKSTECHLAB
RESEARCH_BUILDING_ARRAY[39] = 1  # FACTORYTECHLAB
RESEARCH_BUILDING_ARRAY[41] = 1  # STARPORTTECHLAB
RESEARCH_BUILDING_ARRAY[30] = 1  # FUSIONCORE
RESEARCH_BUILDING_ARRAY[26] = 1  # GHOSTACADEMY
RESEARCH_BUILDING_ARRAY[90] = 1  # EVOLUTIONCHAMBER
RESEARCH_BUILDING_ARRAY[92] = 1  # SPIRE
RESEARCH_BUILDING_ARRAY[93] = 1  # ULTRALISKCAVERN
RESEARCH_BUILDING_ARRAY[901] = 1  # LURKERDEN
RESEARCH_BUILDING_ARRAY[96] = 1  # BANELINGNEST
RESEARCH_BUILDING_ARRAY[97] = 1  # ROACHWARREN
RESEARCH_BUILDING_ARRAY[89] = 1  # SPAWNINGPOOL
RESEARCH_BUILDING_ARRAY[86] = 1  # HATCHERY
RESEARCH_BUILDING_ARRAY[91] = 1  # HYDRALISKDEN
RESEARCH_BUILDING_ARRAY[94] = 1  # INFESTATIONPIT
